# TODO(@mstarr) scope inputs to be per exercise
filegroup(
    name = "data",
    visibility = ["//visibility:public"],
    srcs = [
        "day-01.input",
        "day-02.input",
        "day-03.input",
        "day-04.input",
        "day-05.input",
        "day-06.input",
        "day-07.input",
        "day-08.input",
        "day-09.input",
        "day-10.input",
        "day-11.input",
        "day-12.input",
        "day-13.input",
        "day-14.input",
    ],
)
