load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# http_archive(
#     name = "rules_cc",
#     urls = ["https://github.com/bazelbuild/rules_cc/archive/7bd0e49cfb2237086df89dca9e6ba7a5a5dfb36d.tar.gz"]
# )

http_archive(
    name = "catch2",
    url = "https://github.com/catchorg/Catch2/archive/v3.0.0-preview3.tar.gz",
    strip_prefix="Catch2-3.0.0-preview3"
)
